import type { Product, Category, Review, Coupon, Banner } from '@/types';

export const BANNERS: Banner[] = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80',
    title: 'Grand Living Room Sale',
    subtitle: 'Up to 60% off on Sofas, Sectionals & Accent Chairs',
    cta: 'Shop Sofas',
    link: '/products?category=Sofa%20%26%20Seating',
    bgColor: 'from-stone-900 via-stone-800 to-amber-900',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&q=80',
    title: 'Bedroom Makeover Collection',
    subtitle: 'Premium Beds, Mattresses & Wardrobes — Starting ₹12,999',
    cta: 'Shop Bedroom',
    link: '/products?category=Bedroom',
    bgColor: 'from-slate-900 via-gray-800 to-slate-700',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=1200&q=80',
    title: 'Home Office Essentials',
    subtitle: 'Ergonomic Desks, Chairs & Storage for Peak Productivity',
    cta: 'Shop Office',
    link: '/products?category=Home%20Office',
    bgColor: 'from-blue-950 via-blue-900 to-indigo-900',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=80',
    title: 'Outdoor & Patio Sale',
    subtitle: 'Garden Furniture, Swings & Patio Sets — Up to 45% Off',
    cta: 'Explore Outdoor',
    link: '/products?category=Outdoor',
    bgColor: 'from-green-950 via-emerald-900 to-teal-900',
  },
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Sofa & Seating', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200&q=80', color: 'bg-amber-50 dark:bg-amber-950' },
  { id: '2', name: 'Bedroom', image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=200&q=80', color: 'bg-blue-50 dark:bg-blue-950' },
  { id: '3', name: 'Dining Room', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&q=80', color: 'bg-orange-50 dark:bg-orange-950' },
  { id: '4', name: 'Home Office', image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=200&q=80', color: 'bg-slate-50 dark:bg-slate-950' },
  { id: '5', name: 'Outdoor', image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=200&q=80', color: 'bg-green-50 dark:bg-green-950' },
  { id: '6', name: 'Storage', image: 'https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=200&q=80', color: 'bg-purple-50 dark:bg-purple-950' },
  { id: '7', name: 'Lighting', image: 'https://images.unsplash.com/photo-1513506003901-1e6a35049745?w=200&q=80', color: 'bg-yellow-50 dark:bg-yellow-950' },
  { id: '8', name: 'Home Decor', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=200&q=80', color: 'bg-rose-50 dark:bg-rose-950' },
];

export const BRAND_NAMES = [
  'Urban Ladder', 'Pepperfry', 'Nilkamal', 'Godrej Interio',
  'Durian', 'IKEA', 'Wooden Street', 'Wakefit',
  'HomeTown', 'Fabindia', 'Sleepyhead', 'Featherlite',
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Premium L-Shape Sectional Sofa 5-Seater (Grey)',
    brand: 'Urban Ladder',
    category: 'Sofa & Seating',
    subcategory: 'Sectional Sofas',
    price: 54999,
    originalPrice: 89999,
    discount: 39,
    rating: 4.5,
    reviewCount: 1243,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aaa5b950?w=500&q=80',
    ],
    description: 'Luxurious L-shape sectional sofa with high-density foam seating, sturdy engineered wood frame, and premium woven fabric upholstery. Perfect for large living rooms with ample seating for the whole family.',
    specifications: {
      'Seating Capacity': '5 People',
      'Upholstery': 'Premium Woven Fabric',
      'Frame': 'Engineered Hardwood',
      'Cushion Fill': 'High-Density Foam + Fibre',
      'Dimensions': '280 × 170 × 85 cm',
      'Leg Material': 'Solid Wood (Walnut)',
      'Warranty': '2 Years',
    },
    stock: 12,
    seller: 'Urban Ladder Official',
    tags: ['sofa', 'sectional', 'l-shape', 'living-room'],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: 'p2',
    name: 'King Size Storage Bed with Hydraulic Lift (Walnut Finish)',
    brand: 'Wakefit',
    category: 'Bedroom',
    subcategory: 'Beds',
    price: 32999,
    originalPrice: 54999,
    discount: 40,
    rating: 4.6,
    reviewCount: 2341,
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=500&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&q=80',
    ],
    description: 'King size bed with hydraulic lift mechanism for generous under-bed storage. Premium walnut veneer finish, tufted cushioned headboard, and robust solid wood slats for mattress support.',
    specifications: {
      'Bed Size': 'King (180 × 200 cm)',
      'Material': 'Engineered Wood + Walnut Veneer',
      'Storage': 'Hydraulic Lift (Full Base)',
      'Headboard': 'Cushioned Tufted',
      'Weight Capacity': '250 kg',
      'Assembly': 'Free by Carpenter',
      'Warranty': '3 Years',
    },
    stock: 20,
    seller: 'Wakefit Sleep Solutions',
    tags: ['bed', 'king-size', 'storage', 'bedroom'],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: 'p3',
    name: 'Solid Sheesham Wood 6-Seater Dining Table Set',
    brand: 'Wooden Street',
    category: 'Dining Room',
    subcategory: 'Dining Sets',
    price: 42999,
    originalPrice: 69999,
    discount: 39,
    rating: 4.4,
    reviewCount: 876,
    images: [
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=500&q=80',
      'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=500&q=80',
    ],
    description: 'Handcrafted solid Sheesham wood dining table set for 6. Includes 4 cushioned dining chairs and 2 bench seats. Each piece is unique with natural wood grain — no two are alike.',
    specifications: {
      'Table Size': '180 × 90 × 76 cm',
      'Material': 'Solid Sheesham (Indian Rosewood)',
      'Seats': '6 (4 Chairs + 2 Benches)',
      'Chair Seat': 'Cushioned Fabric Upholstery',
      'Finish': 'Natural Honey & Walnut',
      'Surface': 'Hand-Rubbed Wax Polish',
      'Warranty': '1 Year',
    },
    stock: 8,
    seller: 'Wooden Street Furniture',
    tags: ['dining', 'sheesham', 'wooden', 'set'],
    isNew: true,
  },
  {
    id: 'p4',
    name: 'Ergonomic High-Back Mesh Office Chair with Lumbar Support',
    brand: 'Featherlite',
    category: 'Home Office',
    subcategory: 'Office Chairs',
    price: 18999,
    originalPrice: 29999,
    discount: 37,
    rating: 4.5,
    reviewCount: 3421,
    images: [
      'https://images.unsplash.com/photo-1592495991664-b46c2a1448f4?w=500&q=80',
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500&q=80',
    ],
    description: 'Premium ergonomic office chair with breathable mesh back, adjustable lumbar support, 4D armrests, and synchronized tilt mechanism. Designed for 8+ hour comfort during long work sessions.',
    specifications: {
      'Back': 'Breathable Mesh',
      'Seat': 'Memory Foam Cushion',
      'Armrests': '4D Adjustable',
      'Lumbar Support': 'Height + Depth Adjustable',
      'Height Adjust': 'Pneumatic Gas Lift',
      'Tilt': 'Synchronized + Lock',
      'Weight Capacity': '120 kg',
      'Warranty': '2 Years',
    },
    stock: 35,
    seller: 'Featherlite India',
    tags: ['office-chair', 'ergonomic', 'mesh', 'work'],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: 'p5',
    name: '3-Door Sliding Wardrobe with Full-Length Mirror',
    brand: 'Godrej Interio',
    category: 'Storage',
    subcategory: 'Wardrobes',
    price: 28999,
    originalPrice: 44999,
    discount: 36,
    rating: 4.3,
    reviewCount: 1567,
    images: [
      'https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=500&q=80',
    ],
    description: '3-door sliding wardrobe with a full-length mirror on center panel. Interior includes 2 hanging sections, 4 shelves, and a small drawer unit. Anti-rust, silent-glide hardware.',
    specifications: {
      'Doors': '3 Sliding (Silent Glide)',
      'Mirror': 'Full-Length (Center Door)',
      'Interior': '2 Hanging + 4 Shelves + Drawer',
      'Material': 'Pre-Laminated Particle Board',
      'Dimensions': '213 × 56 × 208 cm',
      'Hardware': 'Anti-Rust Metal',
      'Warranty': '1 Year',
    },
    stock: 15,
    seller: 'Godrej Interio Store',
    tags: ['wardrobe', 'sliding', 'mirror', 'storage'],
    isBestSeller: true,
  },
  {
    id: 'p6',
    name: 'Luxury Push-Back Recliner Chair (Brown Leatherette)',
    brand: 'Durian',
    category: 'Sofa & Seating',
    subcategory: 'Recliners',
    price: 24999,
    originalPrice: 39999,
    discount: 38,
    rating: 4.6,
    reviewCount: 2134,
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&q=80',
    ],
    description: 'Premium push-back recliner with 150° recline angle, armrest cup holders, padded neck pillow, and USB port. Soft leatherette upholstery for easy maintenance. Zero-wall proximity design.',
    specifications: {
      'Type': 'Push-Back Recliner',
      'Upholstery': 'Premium Leatherette (Brown)',
      'Recline Angle': 'Up to 150°',
      'Features': 'Cup Holder, USB Port, Pillow',
      'Frame': 'Solid Hardwood',
      'Weight Capacity': '130 kg',
      'Warranty': '1 Year',
    },
    stock: 18,
    seller: 'Durian Furniture',
    tags: ['recliner', 'sofa', 'chair', 'leatherette'],
    isFeatured: true,
  },
  {
    id: 'p7',
    name: 'Queen Size Upholstered Platform Bed with Tufted Headboard',
    brand: 'Pepperfry',
    category: 'Bedroom',
    subcategory: 'Beds',
    price: 21999,
    originalPrice: 34999,
    discount: 37,
    rating: 4.4,
    reviewCount: 1432,
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&q=80',
    ],
    description: 'Elegant queen size platform bed with deep button-tufted linen upholstered headboard. Sturdy slatted wood frame with center support legs. No box spring required — ready for your mattress.',
    specifications: {
      'Bed Size': 'Queen (160 × 200 cm)',
      'Headboard': 'Button-Tufted Upholstered',
      'Upholstery': 'Premium Linen Fabric',
      'Frame': 'Solid Rubber Wood',
      'Base': 'Slatted (No Box Spring Needed)',
      'Assembly': 'Carpenter Included',
      'Warranty': '1 Year',
    },
    stock: 22,
    seller: 'Pepperfry Home',
    tags: ['bed', 'queen', 'upholstered', 'bedroom'],
    isNew: true,
  },
  {
    id: 'p8',
    name: 'Solid Oak Round Coffee Table with Hairpin Legs',
    brand: 'Urban Ladder',
    category: 'Home Decor',
    subcategory: 'Coffee Tables',
    price: 8499,
    originalPrice: 14999,
    discount: 43,
    rating: 4.3,
    reviewCount: 2341,
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&q=80',
    ],
    description: 'Beautiful round coffee table crafted from solid oak with a lower display shelf for books and plants. Mid-century modern hairpin legs in matte black. Easy DIY assembly.',
    specifications: {
      'Shape': 'Round',
      'Diameter': '80 cm',
      'Height': '45 cm',
      'Material': 'Solid Oak Wood',
      'Legs': 'Matte Black Metal Hairpin',
      'Finish': 'Natural Oak',
      'Weight Capacity': '30 kg',
      'Warranty': '1 Year',
    },
    stock: 45,
    seller: 'Urban Ladder Official',
    tags: ['coffee-table', 'round', 'oak', 'decor'],
    isBestSeller: true,
  },
  {
    id: 'p9',
    name: 'Wall-Mounted Floating TV Unit (Walnut, 180 cm)',
    brand: 'Nilkamal',
    category: 'Storage',
    subcategory: 'TV Units',
    price: 16999,
    originalPrice: 27999,
    discount: 39,
    rating: 4.2,
    reviewCount: 1876,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&q=80',
    ],
    description: 'Contemporary wall-mounted floating TV unit with 2 push-to-open cabinets, open display shelf, and integrated cable management grooves. Fits TVs up to 65". Available in Oak and Walnut.',
    specifications: {
      'Width': '180 cm',
      'Mount': 'Wall-Mounted (Floating)',
      'TV Compatibility': 'Up to 65"',
      'Storage': '2 Push Cabinets + Open Shelf',
      'Material': 'MDF + PU Lacquer',
      'Finish': 'Walnut',
      'Weight Capacity': '40 kg (shelf)',
      'Warranty': '1 Year',
    },
    stock: 28,
    seller: 'Nilkamal Furniture',
    tags: ['tv-unit', 'floating', 'entertainment', 'wall-mount'],
    isBestSeller: true,
  },
  {
    id: 'p10',
    name: '5-Tier Industrial Bookshelf with Metal Frame (Black)',
    brand: 'Pepperfry',
    category: 'Storage',
    subcategory: 'Bookshelves',
    price: 6999,
    originalPrice: 11999,
    discount: 42,
    rating: 4.1,
    reviewCount: 3456,
    images: [
      'https://images.unsplash.com/photo-1594130601742-ac17e56cfece?w=500&q=80',
    ],
    description: 'Industrial-style 5-tier open bookshelf with sturdy black powder-coated metal frame and engineered wood shelves. Perfect for books, décor, and plants. Easy DIY assembly.',
    specifications: {
      'Tiers': '5 Open Shelves',
      'Frame': 'Powder-Coated Steel',
      'Shelves': 'Engineered Wood',
      'Dimensions': '60 × 30 × 180 cm',
      'Color': 'Matte Black + Natural Wood',
      'Max Load/Shelf': '20 kg',
      'Warranty': '6 Months',
    },
    stock: 67,
    seller: 'Pepperfry Home',
    tags: ['bookshelf', 'shelf', 'storage', 'industrial'],
    isBestSeller: true,
  },
  {
    id: 'p11',
    name: 'Outdoor Garden Swing 2-Seater with Canopy & Cushions',
    brand: 'HomeTown',
    category: 'Outdoor',
    subcategory: 'Garden Swings',
    price: 12999,
    originalPrice: 21999,
    discount: 41,
    rating: 4.3,
    reviewCount: 987,
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=500&q=80',
    ],
    description: '2-seater outdoor garden swing with powder-coated steel stand, weather-resistant cushions, and UV-resistant shade canopy. Ideal for balconies, gardens, and patios.',
    specifications: {
      'Seating': '2 Persons',
      'Frame': 'Powder-Coated Steel',
      'Cushion Material': 'Weather-Resistant Polyester',
      'Canopy': 'UV-Resistant Fabric',
      'Weight Limit': '200 kg',
      'Assembly': 'Included',
      'Warranty': '1 Year',
    },
    stock: 20,
    seller: 'HomeTown Decor',
    tags: ['swing', 'garden', 'outdoor', 'patio'],
    isFeatured: true,
  },
  {
    id: 'p12',
    name: 'Solid Wood Writing Desk with 3 Drawers & Cable Port',
    brand: 'Wooden Street',
    category: 'Home Office',
    subcategory: 'Desks',
    price: 14999,
    originalPrice: 24999,
    discount: 40,
    rating: 4.4,
    reviewCount: 1234,
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500&q=80',
    ],
    description: 'Handcrafted solid Sheesham wood writing desk with 3 lockable drawers, built-in cable management port, and non-slip felt pads. Perfect for home offices and study rooms.',
    specifications: {
      'Material': 'Solid Sheesham Wood',
      'Drawers': '3 (with Lock)',
      'Cable Port': 'Built-In Round',
      'Dimensions': '120 × 60 × 76 cm',
      'Finish': 'Natural Teak',
      'Surface': 'Anti-Scratch Laminate',
      'Warranty': '1 Year',
    },
    stock: 24,
    seller: 'Wooden Street Furniture',
    tags: ['desk', 'writing', 'office', 'wood'],
    isNew: true,
  },
  {
    id: 'p13',
    name: "Kids Bunk Bed with Storage Stairs & Study Table",
    brand: 'Urban Ladder',
    category: 'Bedroom',
    subcategory: 'Kids Furniture',
    price: 34999,
    originalPrice: 54999,
    discount: 36,
    rating: 4.5,
    reviewCount: 765,
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=500&q=80',
    ],
    description: '3-in-1 kids bunk bed with storage stairs (each step is a drawer), an integrated pull-out study table, and full-length safety guardrails. Solid rubber wood — no sharp edges.',
    specifications: {
      'Configuration': 'Bunk Bed + Study Table',
      'Mattress Size': 'Single (90 × 190 cm) × 2',
      'Material': 'Solid Rubber Wood',
      'Safety': 'Side Guardrails + Anti-Slip Steps',
      'Storage Drawers': '4 (in stairs)',
      'Study Table': 'Pull-Out Integrated',
      'Warranty': '2 Years',
    },
    stock: 10,
    seller: 'Urban Ladder Official',
    tags: ['bunk-bed', 'kids', 'bedroom', 'storage'],
    isFeatured: true,
  },
  {
    id: 'p14',
    name: 'Bar Cabinet with Wine Rack & Stemware Holder',
    brand: 'Durian',
    category: 'Home Decor',
    subcategory: 'Bar Furniture',
    price: 19999,
    originalPrice: 34999,
    discount: 43,
    rating: 4.2,
    reviewCount: 543,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&q=80',
    ],
    description: 'Premium bar cabinet with 8-bottle wine rack, hanging stemware holder, mirrored interior back panel, and lockable doors. A sophisticated entertaining piece for your living or dining room.',
    specifications: {
      'Wine Rack': '8 Bottles',
      'Glass Holder': 'Stemware (6 glasses)',
      'Doors': 'Lockable Hinged',
      'Back Panel': 'Mirrored Interior',
      'Material': 'MDF with Veneer',
      'Dimensions': '90 × 45 × 130 cm',
      'Warranty': '1 Year',
    },
    stock: 14,
    seller: 'Durian Furniture',
    tags: ['bar', 'cabinet', 'wine', 'decor'],
  },
  {
    id: 'p15',
    name: 'Set of 4 Velvet Dining Chairs with Gold Legs (Teal)',
    brand: 'Featherlite',
    category: 'Dining Room',
    subcategory: 'Dining Chairs',
    price: 11999,
    originalPrice: 19999,
    discount: 40,
    rating: 4.3,
    reviewCount: 1432,
    images: [
      'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=500&q=80',
    ],
    description: 'Set of 4 mid-century modern dining chairs with plush teal velvet upholstery, high-density foam padding, and tapered beech wood legs in a brushed gold finish. Stackable.',
    specifications: {
      'Quantity': '4 Chairs',
      'Upholstery': 'Premium Velvet (Teal)',
      'Legs': 'Solid Beech Wood (Brushed Gold)',
      'Padding': 'High-Density Foam',
      'Style': 'Mid-Century Modern',
      'Stackable': 'Yes',
      'Warranty': '1 Year',
    },
    stock: 30,
    seller: 'Featherlite India',
    tags: ['dining-chairs', 'velvet', 'set', 'modern'],
    isBestSeller: true,
  },
  {
    id: 'p16',
    name: '2-Seater Loveseat Sofa with Cushions (Navy Blue)',
    brand: 'Nilkamal',
    category: 'Sofa & Seating',
    subcategory: 'Loveseats',
    price: 16999,
    originalPrice: 27999,
    discount: 39,
    rating: 4.2,
    reviewCount: 876,
    images: [
      'https://images.unsplash.com/photo-1493663284031-b7e3aaa5b950?w=500&q=80',
    ],
    description: 'Classic 2-seater loveseat with deep button-tufted backrest, solid teak wood legs, and high-resilience foam cushions. Includes 2 decorative throw pillows. Perfect for compact living spaces.',
    specifications: {
      'Seating': '2 Persons',
      'Style': 'Button-Tufted Chesterfield',
      'Upholstery': 'Woven Fabric (Navy Blue)',
      'Legs': 'Solid Teak Wood',
      'Cushion': 'High-Resilience Foam',
      'Includes': '2 Decorative Pillows',
      'Dimensions': '140 × 80 × 85 cm',
      'Warranty': '1 Year',
    },
    stock: 25,
    seller: 'Nilkamal Furniture',
    tags: ['loveseat', 'sofa', 'compact', 'seating'],
    isBestSeller: true,
  },
  {
    id: 'p17',
    name: '5-Drawer Chest in Solid Teak Wood (Natural Finish)',
    brand: 'Godrej Interio',
    category: 'Storage',
    subcategory: 'Chest of Drawers',
    price: 13999,
    originalPrice: 22999,
    discount: 39,
    rating: 4.3,
    reviewCount: 987,
    images: [
      'https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=500&q=80',
    ],
    description: 'Timeless 5-drawer chest in solid teak with dovetail joints, smooth metal side rails, and round wooden knobs. Provides generous, organized storage for clothing and accessories.',
    specifications: {
      'Drawers': '5',
      'Material': 'Solid Teak Wood',
      'Joints': 'Dovetail',
      'Rail': 'Metal Smooth-Glide',
      'Knobs': 'Solid Wood (Round)',
      'Dimensions': '80 × 45 × 115 cm',
      'Warranty': '1 Year',
    },
    stock: 18,
    seller: 'Godrej Interio Store',
    tags: ['chest', 'drawers', 'storage', 'wood'],
    isBestSeller: true,
  },
  {
    id: 'p18',
    name: 'Modern Arc Floor Lamp with Linen Shade (Brushed Brass)',
    brand: 'Pepperfry',
    category: 'Lighting',
    subcategory: 'Floor Lamps',
    price: 4999,
    originalPrice: 8999,
    discount: 44,
    rating: 4.4,
    reviewCount: 2341,
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a35049745?w=500&q=80',
    ],
    description: 'Elegant arc floor lamp with a brushed brass metal pole, natural linen drum shade, and weighted round marble base. Creates warm ambient light. Adjustable arm height up to 165 cm.',
    specifications: {
      'Style': 'Arc / Overhanging',
      'Shade': 'Natural Linen Drum',
      'Pole': 'Brushed Brass Metal',
      'Base': 'Weighted Marble',
      'Height': 'Adjustable up to 165 cm',
      'Bulb': 'E27 Socket (not included)',
      'Max Wattage': '60W',
      'Warranty': '6 Months',
    },
    stock: 56,
    seller: 'Pepperfry Lighting',
    tags: ['floor-lamp', 'arc', 'lighting', 'brass'],
    isBestSeller: true,
  },
  {
    id: 'p19',
    name: 'Cluster Pendant Chandelier with 6 Edison Bulbs (Matte Black)',
    brand: 'HomeTown',
    category: 'Lighting',
    subcategory: 'Pendants',
    price: 7999,
    originalPrice: 13999,
    discount: 43,
    rating: 4.5,
    reviewCount: 1432,
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a35049745?w=500&q=80',
    ],
    description: 'Stunning cluster pendant chandelier with 6 individually adjustable wire drops and Edison-style ST64 bulbs included. Matte black finish ceiling canopy with easy installation.',
    specifications: {
      'Lights': '6 Pendant Drops (Adjustable)',
      'Bulbs': '6 × ST64 Edison (Included)',
      'Finish': 'Matte Black',
      'Cable': 'Textile-Braided (Adjustable)',
      'Install': 'Standard Ceiling Mount',
      'LED': '6 × 4W Warm White',
      'Warranty': '1 Year',
    },
    stock: 32,
    seller: 'HomeTown Decor',
    tags: ['chandelier', 'pendant', 'lighting', 'edison'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'p20',
    name: '4-Seater Outdoor PE Rattan Patio Set with Glass Table',
    brand: 'IKEA',
    category: 'Outdoor',
    subcategory: 'Patio Sets',
    price: 24999,
    originalPrice: 39999,
    discount: 38,
    rating: 4.3,
    reviewCount: 654,
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=500&q=80',
    ],
    description: 'Complete 4-seater patio set with all-weather PE rattan weave, rust-proof powder-coated aluminium frame, tempered glass-top table, and water-resistant removable cushion covers.',
    specifications: {
      'Seating': '4 Persons',
      'Material': 'PE Rattan + Aluminium Frame',
      'Table Top': 'Tempered Glass',
      'Cushion': 'Water-Resistant Polyester',
      'Frame': 'Rust-Proof Powder-Coated',
      'Set Includes': '2-Seat Sofa + 2 Armchairs + Table',
      'Warranty': '2 Years',
    },
    stock: 8,
    seller: 'IKEA India',
    tags: ['patio', 'outdoor', 'rattan', 'garden'],
    isFeatured: true,
  },
  {
    id: 'p21',
    name: 'Wingback Accent Armchair in Emerald Green Velvet',
    brand: 'Fabindia',
    category: 'Sofa & Seating',
    subcategory: 'Armchairs',
    price: 13999,
    originalPrice: 22999,
    discount: 39,
    rating: 4.4,
    reviewCount: 1098,
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&q=80',
    ],
    description: 'Statement wingback accent armchair in luxurious emerald green velvet upholstery with solid wood tapered legs in a brushed gold finish. A bold focal point for any room.',
    specifications: {
      'Style': 'Wingback Accent Chair',
      'Upholstery': 'Crushed Velvet (Emerald Green)',
      'Legs': 'Solid Beech (Brushed Gold)',
      'Cushion': 'High-Density Foam',
      'Dimensions': '80 × 85 × 100 cm',
      'Seating': '1 Person',
      'Warranty': '1 Year',
    },
    stock: 20,
    seller: 'Fabindia Home',
    tags: ['armchair', 'accent', 'velvet', 'wingback'],
    isBestSeller: true,
  },
  {
    id: 'p22',
    name: 'Walnut Wood Bedside Tables with Drawer — Pair',
    brand: 'Wakefit',
    category: 'Bedroom',
    subcategory: 'Nightstands',
    price: 8999,
    originalPrice: 14999,
    discount: 40,
    rating: 4.3,
    reviewCount: 2143,
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&q=80',
    ],
    description: 'Pair of sleek bedside tables in walnut finish, each with a smooth-glide drawer and open bottom shelf. Brushed gold handle hardware. Minimalist design for any bedroom style.',
    specifications: {
      'Quantity': '2 Units (Pair)',
      'Material': 'Engineered Wood (Walnut Veneer)',
      'Storage': '1 Drawer + 1 Open Shelf',
      'Handle': 'Brushed Gold Bar Pull',
      'Dimensions': '45 × 35 × 55 cm (each)',
      'Assembly': 'Easy DIY',
      'Warranty': '1 Year',
    },
    stock: 40,
    seller: 'Wakefit Sleep Solutions',
    tags: ['nightstand', 'bedside', 'bedroom', 'pair'],
    isBestSeller: true,
  },
  {
    id: 'p23',
    name: 'Memory Foam King Mattress with Cooling Gel (10 Inch)',
    brand: 'Sleepyhead',
    category: 'Bedroom',
    subcategory: 'Mattresses',
    price: 24999,
    originalPrice: 44999,
    discount: 44,
    rating: 4.6,
    reviewCount: 4321,
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500&q=80',
    ],
    description: '10-inch king memory foam mattress with cooling gel-infused comfort layer, motion isolation, and pressure-relieving foam base. Includes washable knitted cover. 100-night free trial.',
    specifications: {
      'Size': 'King (180 × 200 cm)',
      'Thickness': '10 Inches',
      'Layers': 'Cooling Gel + Memory Foam + Base Foam',
      'Cover': 'Washable Knitted Fabric',
      'Trial': '100 Nights Risk-Free',
      'Motion Isolation': 'Yes',
      'Warranty': '10 Years',
    },
    stock: 50,
    seller: 'Sleepyhead Mattresses',
    tags: ['mattress', 'memory-foam', 'king', 'sleep'],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: 'p24',
    name: 'Set of 3 Solid Pine Floating Wall Shelves (Natural)',
    brand: 'Urban Ladder',
    category: 'Home Decor',
    subcategory: 'Wall Shelves',
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    rating: 4.2,
    reviewCount: 5678,
    images: [
      'https://images.unsplash.com/photo-1594740516742-af1d06e4f0b5?w=500&q=80',
    ],
    description: 'Set of 3 solid pine wood floating wall shelves (S, M, L) with concealed heavy-duty L-brackets. Includes wall anchors and screws. Perfect for plants, books, frames, and décor.',
    specifications: {
      'Quantity': '3 Shelves (S, M, L)',
      'Material': 'Solid Pine Wood',
      'Finish': 'Natural Clear Lacquer',
      'Max Load': '15 kg each',
      'Brackets': 'Concealed Heavy-Duty',
      'Includes': 'Brackets + Anchors + Screws',
      'Warranty': '6 Months',
    },
    stock: 89,
    seller: 'Urban Ladder Official',
    tags: ['wall-shelf', 'floating', 'decor', 'pine'],
    isBestSeller: true,
  },
];

export const HOME_REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Priya Sharma',
    rating: 5,
    comment: 'The L-shape sectional sofa is absolutely stunning! The quality is premium and the delivery + assembly team were professional. My living room now looks like a showroom. Totally worth it!',
    date: '2026-07-15',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&q=80',
  },
  {
    id: 'r2',
    userName: 'Rahul Verma',
    rating: 4,
    comment: 'Bought the King Storage Bed with hydraulic lift. The mechanism is buttery smooth and provides massive storage space. Build quality is top-notch. Highly recommend WoodNest!',
    date: '2026-07-08',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&q=80',
  },
  {
    id: 'r3',
    userName: 'Anjali Patel',
    rating: 5,
    comment: 'The Sheesham dining table set is a masterpiece — each piece has unique natural grain patterns. It feels truly handcrafted. Sturdy, beautiful, and every guest compliments it!',
    date: '2026-07-20',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80',
  },
  {
    id: 'r4',
    userName: 'Vikram Singh',
    rating: 5,
    comment: 'Ordered the ergonomic mesh office chair for my WFH setup — my back pain completely disappeared after 2 weeks. The lumbar support is exceptional. Best investment of the year!',
    date: '2026-07-25',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&q=80',
  },
  {
    id: 'r5',
    userName: 'Meera Krishnan',
    rating: 4,
    comment: 'The Sleepyhead memory foam mattress transformed my sleep overnight! The cooling gel layer actually works — no more sweaty nights. The 100-night trial gave me total confidence to buy.',
    date: '2026-07-30',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&q=80',
  },
  {
    id: 'r6',
    userName: 'Arjun Mehta',
    rating: 5,
    comment: 'Got the outdoor rattan patio set for our terrace — incredible quality for the price! The aluminium frame held up through monsoon rains without any rust. Garden looks beautiful now!',
    date: '2026-08-01',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&q=80',
  },
];

export const COUPONS: Coupon[] = [
  { code: 'FIRST10', discount: 10, type: 'percentage', minOrder: 2000 },
  { code: 'SAVE500', discount: 500, type: 'flat', minOrder: 15000 },
  { code: 'HOME15', discount: 15, type: 'percentage', minOrder: 10000 },
];

export const OFFER_TEXTS = [
  '🏡 New Home Offer: 10% off on your first order | Code: FIRST10',
  '🛋️ Sofa Bonanza: Up to 60% off on premium sectionals & recliners',
  '🚚 Free delivery + free assembly on orders above ₹15,000',
  '⚡ Flash Sale every day at 12 PM — Save up to 50% on selected furniture',
  '💳 Extra 5% off with HDFC Credit Cards on orders above ₹20,000',
  '🌿 Sustainably sourced solid wood furniture — crafted to last generations',
  '⭐ 100-Night Mattress Trial | No-cost EMI from ₹999/month available',
];

export const FLASH_SALE_IDS = ['p1', 'p4', 'p8', 'p10', 'p18', 'p22', 'p23', 'p24'];
export const TRENDING_IDS = ['p1', 'p2', 'p4', 'p6', 'p13', 'p19', 'p23'];
export const BEST_SELLER_IDS = ['p2', 'p5', 'p8', 'p9', 'p15', 'p17', 'p21', 'p22'];
export const NEW_ARRIVAL_IDS = ['p3', 'p7', 'p12', 'p19', 'p20'];
